repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1 # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        exclude: ^data/
        additional_dependencies: [types-PyYAML==6.0.12.12, types-cachetools]
        args: [--ignore-missing-imports, --explicit-package-base]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        exclude: ^(docs)
